name: React build Check
on: 
  push:
    branches: [ dev, main ]

jobs:
  forked_repo_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code.
      uses: actions/checkout@v3

    - name: Install Dependencies 
      run: npm install
      working-directory: "./client"

    - name: npm build                  
      run: npm run build
      working-directory: "./client"
